#!/bin/bash

output_dir="$XDG_CONFIG_HOME/yadm/synced-files"

# list files in .local/bin
find "$HOME/.local/bin/" -type f -executable -printf "\n%f\n" > "$output_dir/localbin-list.txt"

# list packages installed "manually" by zypper
zypper se -i | grep -v "| product$" | grep -v "| pattern$" | grep "^i+" |\
grep -v "^python3" | grep -v "^lib" |\
grep -v "^patterns-" | grep -v "^qt6-" | grep -v "^yast2" |\
sed -i -e 's/i+ | //g' -e 's/ *| package//g' "$output_dir/zypper-packages.txt"

# list autostart entries
find "$HOME/.config/autostart/" -name "*.desktop" -type f -printf "\n%f\n" > "$output_dir/autostart-list.txt"

# list locally installed fonts (/!\ NOT system or package manager)
find "$HOME/.local/share/fonts/" -type f -not -name ".uuid" -printf "%f\n" |\
sort | uniq --check-chars=10 > "$output_dir/fonts.txt"

# save nordvpn whitelist
nordvpn settings | grep "Allowlisted subnets:" -A 99 | tail -n +2 | sed "s/\t//g" > "$output_dir/nordvpn-whitelist.txt"
