[Audio]
PreferredLanguage=eng
Volume=100

[General]
FileDialogLastLocation=file:///home/zeus/Videos/Shows/tgyh/Thank God You're Here/Season 6
FloatingFooterTrigger=BottomMouseMovement
LastPlayedFile=file:///home/zeus/Videos/Series/animated/Krapopolis.S01.COMPLETE.720p.HULU.WEBRip.x264-GalaxyTV%5BTGx%5D/Krapopolis.S01E02.720p.HULU.WEBRip.x264-GalaxyTV.mkv
LastUrl=https://www.youtube.com/watch?v=bQRHfIqpTgQ
ShowHeader=false
ShowPreviewThumbnail=true
UseSingleInstance=true
Volume=100

[Mouse]
Left=
Middle=playPauseAction

[Playback]
MinDurationToSavePosition=0
OpenLastPlayedFile=true
PlayOnResume=false
RestoreFilePosition=true
SavePositionInterval=10
SeekToLastPosition=true
UseHWDecoding=true

[Playlist]
CanToggleWithMouse=false
PlaybackBehavior=StopAfterLast

[RecentFiles]
File1[$e]=$HOME/Downloads/Taskmaster (US) - S01E01 - Physics WEBDL-720p.mkv
File10[$e]=$HOME/Downloads/dreadnought.mp4
File2[$e]=$HOME/Videos/Series/anime/Chainsaw.Man.S01.Complete.2022.1080p.WEBRip.Dual.Audio.AAC.H.265-Hodl/Chainsaw Man S01E01 2022 1080p WEBRip Dual Audio AAC H.265-Hodl.mkv
File3[$e]=$HOME/Torrents/TV Series/animated/Warhammer.TV.SiteRip.2025.06.26.1080p.WEB.H264-Altansar/5 - Animations/Astartes/Astartes - 1 - Astartes.mkv
File4[$e]=$HOME/Torrents/Audiobooks/Black Legion/Black Legion꞉ Black Legion꞉ Warhammer 40,000, Book 2.m4b
File5[$e]=$HOME/Torrents/Audiobooks/Black Legion/Black Legion꞉ Black Legion꞉ Warhammer 40,000, Book 2.cue
File6[$e]=$HOME/Videos/Films/Ultramarines.A.Warhammer.40000.Movie.2010.1080p.BluRay.x265-RARBG/Sanet.st.Ultramarines.A.Warhammer.40000.Movie.2010.1080p.BluRay.x265-RARBG.mp4
File7[$e]=$HOME/Videos/Films/Ultramarines A Warhammer 40,000 Movie BD-Rip 720p/Ultramarines A Warhammer 40,000 Movie BD-Rip 720p.mkv
File8[$e]=$HOME/Videos/Series/animated/Warhammer TV/00. Angels of Death Origins - 00 (WEBRip 1920x1080 x264 AAC Rus + Eng) (1) (1).mkv
File9[$e]=$HOME/Torrents/TV Series/live-action/www.UIndex.org    -    Guy.Montgomerys.Guy.Mont.Spelling.Bee.S01E07.1080p.HDTV.H264-CBFM/guy.montgomerys.guy.mont.spelling.bee.s01e07.1080p.hdtv.h264-cbfm.mkv
Name1[$e]=Taskmaster (US) - S01E01 - Physics WEBDL-720p.mkv
Name10[$e]=dreadnought.mp4
Name2[$e]=Chainsaw Man S01E01 2022 1080p WEBRip Dual Audio AAC H.265-Hodl.mkv
Name3[$e]=Astartes - 1 - Astartes.mkv
Name4[$e]=Black Legion꞉ Black Legion꞉ Warhammer 40,000, Book 2.m4b
Name5[$e]=Black Legion꞉ Black Legion꞉ Warhammer 40,000, Book 2.cue
Name6[$e]=Sanet.st.Ultramarines.A.Warhammer.40000.Movie.2010.1080p.BluRay.x265-RARBG.mp4
Name7[$e]=Ultramarines A Warhammer 40,000 Movie BD-Rip 720p.mkv
Name8[$e]=00. Angels of Death Origins - 00 (WEBRip 1920x1080 x264 AAC Rus + Eng) (1) (1).mkv
Name9[$e]=guy.montgomerys.guy.mont.spelling.bee.s01e07.1080p.hdtv.h264-cbfm.mkv

[Shortcuts]
screenshotAction=
seekBackwardBigAction=
seekForwardBigAction=
seekNextChapterAction=PgDown
seekPreviousChapterAction=PgUp
subtitleToggleAction=C
volumeDownAction=Down
volumeUpAction=Up

[Subtitles]
AllowOnBlackBorders=true
BorderSize=1
FontSize=12
PreferredLanguage=eng
PreferredTrack=1
SubtitlesFolders=subs,Subs
